apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: init-container
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  serverImage: k8ssandra/cass-management-api:3.11.10-v0.1.24
  serverType: cassandra
  serverVersion: 3.11.10
  disableSystemLoggerSidecar: true
  dockerImageRunsAsCassandra: true
  podTemplateSpec:
    spec:
      containers: []
      initContainers:
      - name: hello
        image: busybox
        args:
        - /bin/sh
        - -c
        - echo Hello World
